---
title: Cookies Policy and Terms of Use
output: 
  html_document: 
    toc: yes
---
### Cookies Policy
#### Google Analytics Cookies

This site uses Google Analytics which is one of the most widespread and trusted analytics solution on the web for helping us to understand how you use the site and ways that we can improve your experience. These cookies may track things such as how long you spend on the site and the pages that you visit so we can continue to produce engaging content.
For more information on Google Analytics cookies, see [the official Google Analytics page](https://developers.google.com/analytics/resources/concepts/gaConceptsCookies). 

We also use Google Analytics Advertising Features that collects and process some information about your interests and an anonymized sociodemographic profile. These data may be subsequently analyzed in combination with data on your search queries (whenever you use Google Search) and/or data generating whenever you visit web pages of any of our hosting partner github.com 

To prevent gathering information of this kind, you can use a special tool provided by Google. [Click here](https://tools.google.com/dlpage/gaoptout/?hl=en) to find out more and apply this tool. 
You can also read more about cookies used by Google on [Google's official page](http://www.google.com/intl/en/policies/technologies/types/).
		
### Terms of Use

By accessing this web site, you are agreeing to be bound by these Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this web site are protected by applicable copyright and trade mark law.

#### Use License

Permission is granted to temporarily download one copy of the materials (information or software) on danielszulc.intelligence-data.net for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not: modify or copy the materials; use the materials for any commercial purpose, or for any public display (commercial or non-commercial); attempt to decompile or reverse engineer any software contained on danielszulc.intelligence-data.net; remove any copyright or other proprietary notations from the materials; or transfer the materials to another person or “mirror” the materials on any other server. This license shall automatically terminate if you violate any of these restrictions and may be terminated by Daniel Szulc at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.

#### Disclaimer

The materials on danielszulc.intelligence-data.net are provided “as is”. Daniel Szulc makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Daniel Szulc does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on this site or otherwise relating to such materials or on any sites linked to this site.

Any views or opinions presented on danielszulc.intelligence-data.net are solely those of Daniel Szulc and do not represent opinions any of Daniel Szulc's related and affiliate companies.

#### Limitations

In no event shall Daniel Szulc (or his suppliers) be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on danielszulc.intelligence-data.net, even if Daniel Szulc or a representative authorized by Daniel Szulc has been notified orally or in writing of the possibility of such damage.

Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.

#### Revisions and Errata

The materials appearing on danielszulc.intelligence-data.net could include technical, factual, typographical, or photographic errors. Daniel Szulc does not warrant that any of the materials on this site are accurate, complete, or current. Daniel Szulc may make changes to the materials contained on this site at any time without notice. Daniel Szulc does not, however, make any commitment to update the materials.

#### Links

Daniel Szulc has not necessarily reviewed all of the sites linked to on this site, and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement. Use of any such linked web site is at the user’s own risk.

#### Site Terms of Use Modifications

These terms of use may be modified at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.

#### Governing Law

Any claim relating to danielszulc.intelligence-data.net shall be governed by the laws of the Republic of Poland.

This Agreement constitutes the entire agreement between you and Daniel Szulc and govern your use of danielszulc.intelligence-data.net, superseding any prior agreements between You and Daniel Szulc relating to the subject matter hereof. This Agreement and the relationship between you and Daniel Szulc shall be governed by the laws of the State of California without regard to its conflict of law provisions.

The provisions of the United Nations convention on contracts for the international sale of goods and the uniform computer informations transactions act will not aply to this agreement, and are hereby disclaimed. You and Daniel Szulc agree to submit to the personal and exclusive jurisdiction of the courts located in Warsaw, Poland The section titles in this Agreement are for convenience only and have no legal or contractual effect. As used herein, the term “including” means “including without limitation”.